### ISSUE TITLE
undefined: resourceIconPng

### ISSUE THREAD

**Issue by pnunn** [fyne-io/examples#30] opened 2021-05-07 06:56 UTC
Hi Guys,
Trying to run the examples and have hit an issue.

I've simply done a git clone into a pretty much new machine.  Have managed to run fyne_demo OK, but when I try and run main.go from this repo I'm getting

./main.go:36:12: undefined: resourceIconPng

I can see that it exists in data.go, but for some reason isn't getting picked up by the looks of things.

Peter.

**Comment by Jacalz** [comment] 2021-05-07 08:09
What command were you using to build it? Does a regular `go build` work?

**Comment by pnunn** [comment] 2021-05-07 08:18
I'm in the fyne/examples subdirectory, and just run go run main.go.

There is no fyne_demo directory in this repo is there?

**Comment by Jacalz** [comment] 2021-05-07 08:47
Sorry. I edited the comment after I sent it. Ignore the fyne_demo part.

**Comment by Jacalz** [comment] 2021-05-07 10:29
The issue is because of how you are running it. Running using `go run main.go` only runs `main.go` and no other files, thus resulting in the error described above.

**Comment by pnunn** [comment] 2021-05-07 11:41
Um.. OK, then how should I be running the examples.. the instructions say

You can start the main example app that links to all the others by running

go run main.go

On the readme of the repo.

**Comment by Jacalz** [comment] 2021-05-07 12:18
I think the documentation needs to be updated. Either `go run .` or  `go build` (need to run the binary in that case of course) should do the trick.

**Comment by andydotxyz** [comment] 2021-05-07 17:17
Apologies, the documentation got out of date.
Fixed now.

**Closed as completed by andydotxyz** 2021-05-07 17:17 UTC
