### ISSUE TITLE
./main failed to run

### ISSUE THREAD

**Issue by bruceauyeung** [fyne-io/examples#9] opened 2019-01-25 08:51 UTC
`go build main.go` is ok, but `./main` failed to run with error:
~~~
# ./main
GLFW: An uncaught error has occurred: PlatformError: X11: RandR gamma ramp support seems broken
GLFW: Please report this bug in the Go package immediately.
2019/01/25 16:41:09 PlatformError: X11: RandR monitor support seems broken
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e6542]

goroutine 1 [running, locked to thread]:
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.(*Window).MakeContextCurrent(0x0)
        /root/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/context.go:16 +0x22
fyne.io/fyne/driver/gl.(*gLDriver).CreateWindow.func1()
        /root/go/src/fyne.io/fyne/driver/gl/window.go:469 +0x11c
fyne.io/fyne/driver/gl.runOnMain(0xc00008d530)
        /root/go/src/fyne.io/fyne/driver/gl/loop.go:31 +0xac
fyne.io/fyne/driver/gl.(*gLDriver).CreateWindow(0xc00000c8a0, 0x8f6d70, 0x8, 0xc00008d500, 0xc0000a5ca8)
        /root/go/src/fyne.io/fyne/driver/gl/window.go:454 +0x99
fyne.io/fyne/app.(*fyneApp).NewWindow(0xc0000666c0, 0x8f6d70, 0x8, 0xc0000a5cc8, 0x10)
        /root/go/src/fyne.io/fyne/app/app.go:33 +0x47
main.welcome(0x971e80, 0xc0000666c0)
        /root/go/src/github.com/fyne-io/examples/main.go:24 +0x5e
main.main()
        /root/go/src/github.com/fyne-io/examples/main.go:63 +0x53b

~~~

OS: same error with CentOS 7, Ubuntu 16.04.4 LTS

RandR related packages for CentOS:
~~~
# rpm -qa|grep -i randr
libXrandr-1.5.1-2.el7.x86_64
libXrandr-devel-1.5.1-2.el7.x86_64
~~~
RandR related packages for Ubuntu:
~~~
# dpkg -l|grep -i randr
ii  libxcb-randr0:amd64                             1.11.1-1ubuntu1                                          amd64        X C Binding, randr extension
ii  libxcb-randr0-dev:amd64                         1.11.1-1ubuntu1                                          amd64        X C Binding, randr extension, development files
ii  libxrandr-dev:amd64                             2:1.5.0-1                                                amd64        X11 RandR extension library (development headers)
ii  libxrandr2:amd64                                2:1.5.0-1                                                amd64        X11 RandR extension library
ii  x11proto-randr-dev                              1.5.0-1                                                  all          X11 RandR extension wire protocol

~~~

**Comment by andydotxyz** [comment] 2019-01-25 11:12
Apologies you have hit this problem! Are you running locally or is there an X-over-ssh in use?
This is a peculiar error so I'm just looking for any strangeness that might cause it.
Do you know what graphics card this is on?

**Comment by bruceauyeung** [comment] 2019-01-28 07:09
X-over-ssh,  i logined in linux server from windows 7 64bit( same problem from windows xp),
on windows i use MobaXterm as X server
graphical card on windows xp: AMD 760G
graphical card on windows 7 64bit: this host is a cloud virtual machine, so i think the video card is also virtual: mv video hook driver2 , Red hat  QXL GPU
graphical card on centos 7: this is a blade server
>\# lspci|grep -i vga
08:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] ES1000 (rev 02)

graphical card on ubuntu: this is a normal PC
>\# lspci|grep -i vga
01:00.0 VGA compatible controller: NVIDIA Corporation GT218 [GeForce 405] (rev a2)

@andydotxyz

**Comment by andydotxyz** [comment] 2019-01-28 23:30
Hi thanks for the information. I think this is not supported by the 3.2 GLFW which we use unfortunately. I think it is fixed in 3.3 which hopefully will be available for the Go bindings soon.

Sorry I can’t move this forward quicker

**Comment by bruceauyeung** [comment] 2019-01-29 01:07
> this is not supported by the 3.2 GLFW

what  is not supported? X over SSH ?

**Comment by andydotxyz** [comment] 2019-01-29 09:56
Yes that is my understanding.
Maybe it’s a bug in the bindings. 
I heard that it was somehow related to the headless support, but let me know if you have more information.

**Comment by andydotxyz** [comment] 2019-03-18 19:45
I have updated the GL code so it only requires 2.0 instead of 3.2 - there is a chance it could have helped this. Would you be able to test again and see if it helps?

Thanks

**Comment by bruceauyeung** [comment] 2019-03-19 06:35
the window can now be displayed and everything seems ok except that there still  are errors:

> \# ./main
GLFW: An uncaught error has occurred: PlatformError: X11: RandR gamma ramp support seems broken
GLFW: Please report this bug in the Go package immediately.
2019/01/25 16:41:09 PlatformError: X11: RandR monitor support seems broken

@andydotxyz

**Comment by andydotxyz** [comment] 2019-03-19 12:40
This is good news thanks.
I have seen that error on simpler setups - such as Xephyr. I don't know the root cause yet, and I'm not very worried. I will close this issue now, I hope you agree the root problem is resolved.

**Closed as completed by andydotxyz** 2019-03-19 12:40 UTC
